package com.panda.tauth.ui.list

import androidx.compose.runtime.Stable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.panda.tauth.Outcome
import com.panda.tauth.ui.ClipboardCopy
import com.panda.tauth.ui.CopyResult
import com.panda.tauth.vault.EntryChangeError
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlin.time.Duration.Companion.seconds

internal const val CODE_SUBJECT = "Code"
internal const val URI_SUBJECT = "URI"
internal const val COPY_REFUSED_NOTICE = "The clipboard would not take it"

// The generate control goes dead for this long after a generation: two presses inside the time it
// takes to see the first land would spend two counter values.
private const val GENERATE_COOLDOWN_SECONDS = 3

// How long a bare confirmation stands when no clipboard clear is scheduled for it to count down.
private const val NOTICE_SECONDS = 3

internal fun copiedNotice(subject: String, secondsLeft: Int?): String =
    if (secondsLeft == null) "$subject copied" else "$subject copied — the clipboard clears in $secondsLeft s"

private class CopyNotice(val entryId: String, val message: String)

// What the rows show that the vault does not hold. All of it ends with the composition that owns
// this, which takes a generated code off the screen when the list is left or the vault locks.
@Stable
internal class RowState {
    var generated by mutableStateOf(emptyMap<String, String>())
        private set

    var coolingDown by mutableStateOf(emptySet<String>())
        private set

    private var notice by mutableStateOf<CopyNotice?>(null)

    private var noticeJob: Job? = null

    fun noticeFor(entryId: String): String? = notice?.takeIf { it.entryId == entryId }?.message

    fun hideCode(entryId: String) {
        generated = generated - entryId
    }

    fun generate(scope: CoroutineScope, entryId: String, run: suspend (String) -> Outcome<String, EntryChangeError>) {
        // Two presses inside one frame both read the same `enabled` flag, so the refusal is here and
        // not on the control: each press past the first would spend a counter value of its own.
        if (entryId in coolingDown) return
        coolingDown = coolingDown + entryId
        scope.launch {
            when (val outcome = run(entryId)) {
                // A refused write left the stored counter where it was, so no code is shown for a
                // position the file does not carry and the control comes straight back.
                is Outcome.Failure -> coolingDown = coolingDown - entryId

                is Outcome.Success -> {
                    generated = generated + (entryId to outcome.value)
                    delay(GENERATE_COOLDOWN_SECONDS.seconds)
                    coolingDown = coolingDown - entryId
                }
            }
        }
    }

    fun copy(
        scope: CoroutineScope,
        entryId: String,
        subject: String,
        text: String,
        clipboard: ClipboardCopy,
        clearSeconds: Int,
    ) {
        when (clipboard.copy(text, clearSeconds)) {
            CopyResult.REFUSED -> hold(scope, entryId, COPY_REFUSED_NOTICE, NOTICE_SECONDS)

            // The countdown on screen is the one the clipboard is running, so the row and the
            // platform agree about how long the text is out of the vault's reach.
            CopyResult.COPIED ->
                if (clearSeconds > 0) {
                    countDown(scope, entryId, subject, clearSeconds)
                } else {
                    hold(scope, entryId, copiedNotice(subject, null), NOTICE_SECONDS)
                }
        }
    }

    private fun hold(scope: CoroutineScope, entryId: String, message: String, seconds: Int) {
        noticeJob?.cancel()
        noticeJob = scope.launch {
            notice = CopyNotice(entryId, message)
            delay(seconds.seconds)
            notice = null
        }
    }

    private fun countDown(scope: CoroutineScope, entryId: String, subject: String, clearSeconds: Int) {
        noticeJob?.cancel()
        noticeJob = scope.launch {
            for (left in clearSeconds downTo 1) {
                notice = CopyNotice(entryId, copiedNotice(subject, left))
                delay(1.seconds)
            }
            notice = null
        }
    }
}
